"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const dash_1 = require("../controllers/dash");
const suppliers_1 = require("../controllers/suppliers");
const products_1 = require("../controllers/products");
const orders_1 = require("../controllers/orders");
const employees_1 = require("../controllers/employees");
const customers_1 = require("../controllers/customers");
const search_1 = require("../controllers/search");
const idHandler_1 = require("../middleware/idHandler");
const searchHandler_1 = require("../middleware/searchHandler");
const router = (0, express_1.default)();
router.get("/dash", dash_1.Dash);
router.get("/suppliers", suppliers_1.Suppliers);
router.get("/supplier/:id?", idHandler_1.idHandler, suppliers_1.Supplier);
router.get("/products", products_1.Products);
router.get("/product/:id?", idHandler_1.idHandler, products_1.Product);
router.get("/orders", orders_1.Orders);
router.get("/order/:id?", idHandler_1.idHandler, orders_1.Order);
router.get("/employees", employees_1.Employees);
router.get("/employee/:id?", idHandler_1.idHandler, employees_1.Employee);
router.get("/customers", customers_1.Customers);
router.get("/customer/:id?", idHandler_1.idHandler, customers_1.Customer);
router.get("/search/:type?/:searchWord?", searchHandler_1.searchHandler, search_1.Search);
exports.default = router;
